DROP DATABASE IF EXISTS cloud;
CREATE DATABASE IF NOT EXISTS cloud;
DROP USER IF EXISTS 'cloud'@'%';
CREATE USER IF NOT EXISTS 'cloud'@'%';
ALTER USER 'cloud'@'%' IDENTIFIED BY 'cloud';
GRANT SELECT ON cloud.* TO 'cloud'@'%';
GRANT DELETE ON cloud.* TO 'cloud'@'%';
GRANT UPDATE ON cloud.* TO 'cloud'@'%';
GRANT ALTER ON cloud.* TO 'cloud'@'%';
GRANT CREATE ON cloud.* TO 'cloud'@'%';
GRANT CREATE VIEW ON cloud.* TO 'cloud'@'%';
GRANT DROP ON cloud.* TO 'cloud'@'%';
GRANT GRANT OPTION ON cloud.* TO 'cloud'@'%';
GRANT INDEX ON cloud.* TO 'cloud'@'%';
GRANT INSERT ON cloud.* TO 'cloud'@'%';
GRANT REFERENCES ON cloud.* TO 'cloud'@'%';
GRANT SHOW VIEW ON cloud.* TO 'cloud'@'%';
GRANT TRIGGER ON cloud.* TO 'cloud'@'%';
FLUSH PRIVILEGES;